### ISSUE TITLE
Idea: make PwnedPasswordValidator's `count` configurable

### ISSUE THREAD

**Issue by kevinrenskers** [QueraTeam/django-pwned#3]
Great library! We like the idea of using PwnedPasswordValidator in one of our projects, but we feel that it would be best to make the `count` value where it counts as a failure configurable. haveibeenpwned contains over half a billion leaked passwords, which of course will contain completely unique passwords used by one person before. It's probably not necessary to block all of these passwords from being used ever again - a count of 1 does not mean it is "commonly used on other websites". We'd only want to block a password if it has a count of 1.000 for example.

**Comment by mjnaderi** [comment]
Hi @kevinrenskers 
Thanks for your suggestion. I added the `count_threshold` option in `v1.2.0`.
